
name: First Workflow

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Step 1 Complete
        run: echo "Step 1 Complete!"
  job2:
    runs-on: ubuntu-latest
    needs: job1


    steps:
     - name: Cowsays Action
       uses: mscoutermarsh/cowsays-action@master
       with:
                        text: "Ready for prod-ship it!"
                        color: "magenta"